### For Nobu's photos

In [36]:
import os
import cv2
import numpy as np

folder = 'data/N/'

for i in range(1, 11, 1):
    day = 't'+ str(i)
    path = folder + 'experiment3/' + day + '/banana'
    idx = 0
    for filename in os.listdir(path):
        if filename.endswith('.jpg'):
            num = ''
            j = 0
            while True:
                if filename[j] == 't':
                    break
                else:
                    num = num + filename[j]
                    j += 1
            print(filename)
            print(num)
            #############################################
            # After selecting the correct HSV
            #############################################
            img = cv2.imread(path + '/' + filename)
            #print(img)
            #convert to HSA
            imgHSV = cv2.cv2.cvtColor(img, cv2.COLOR_BGR2HSV)
            #select the filtered image
            lower = np.array([21,36,44])
            upper = np.array([55,255,255])
            #filtered image
            mask = cv2.inRange(imgHSV, lower, upper)
            #using filtered images to create new image 
            #this is adding two images together 
            imgResult = cv2.bitwise_and(img,img, mask = mask)
 
            # =============================================================================
            # img = imgResult.copy() 
            # imgContour = imgResult.copy()
            # =============================================================================

            imgGray = cv2.cvtColor(imgResult, cv2.COLOR_BGR2GRAY)
            #sigma, the higher the value, the more blur you get
            imgBlur = cv2.GaussianBlur(imgGray,(7,7),1)

            (cnts, _) = cv2.findContours(imgBlur, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE) 
        #    idx = 0 
            for c in cnts: 
                area = cv2.contourArea(c)
                if area > 1000:
                    x,y,w,h = cv2.boundingRect(c) 
                    if w>400 and h>400:
                        print('check4')
                        idx+=1 
                        new_img=imgResult[y:y+h,x:x+w] 
                        print('banana_images/N/' +day + '/'+ num + '.png')
                        cv2.imwrite('banana_images/N/' +day + '/'+ num + '.png', new_img) 

1t1.jpg
1
check4
banana_images/N/t1/1.png
3t1.jpg
3
check4
banana_images/N/t1/3.png
7t1.jpg
7
check4
banana_images/N/t1/7.png
5t1.jpg
5
check4
banana_images/N/t1/5.png
2t1.jpg
2
check4
banana_images/N/t1/2.png
4t1.jpg
4
check4
banana_images/N/t1/4.png
check4
banana_images/N/t1/4.png
6t1.jpg
6
check4
banana_images/N/t1/6.png
8t1.jpg
8
check4
banana_images/N/t1/8.png
3t2.jpg
3
check4
banana_images/N/t2/3.png
1t2.jpg
1
check4
banana_images/N/t2/1.png
5t2.jpg
5
check4
banana_images/N/t2/5.png
7t2.jpg
7
check4
banana_images/N/t2/7.png
2t2.jpg
2
check4
banana_images/N/t2/2.png
6t2.jpg
6
check4
banana_images/N/t2/6.png
4t2.jpg
4
check4
banana_images/N/t2/4.png
check4
banana_images/N/t2/4.png
8t2.jpg
8
check4
banana_images/N/t2/8.png
3t3.jpg
3
check4
banana_images/N/t3/3.png
1t3.jpg
1
check4
banana_images/N/t3/1.png
5t3.jpg
5
check4
banana_images/N/t3/5.png
7t3.jpg
7
check4
banana_images/N/t3/7.png
2t3.jpg
2
check4
banana_images/N/t3/2.png
6t3.jpg
6
check4
banana_images/N/t3/6.png
4t3.jpg
4
ch

### For Bill's photos

In [49]:
import os
import cv2
import numpy as np

folder = 'data/B/experiment2/'

for i in range(1, 2, 1):
    day = 't'+ str(i)
    path = folder + day 
    idx = 0
    for filename in os.listdir(path):
        if filename.endswith('.jpg'):
            num = ''
            j = 0
            while True:
                if filename[j] == 't':
                    break
                else:
                    num = num + filename[j]
                    j += 1
            print(filename)
            print(num)
            #############################################
            # After selecting the correct HSV
            #############################################
            img = cv2.imread(path + '/' + filename)
            #print(img)
            #convert to HSA
            imgHSV = cv2.cv2.cvtColor(img, cv2.COLOR_BGR2HSV)
            #select the filtered image
            lower = np.array([21,36,44])
            upper = np.array([55,255,255])
            #filtered image
            mask = cv2.inRange(imgHSV, lower, upper)
            #using filtered images to create new image 
            #this is adding two images together 
            imgResult = cv2.bitwise_and(img,img, mask = mask)
 
            # =============================================================================
            # img = imgResult.copy() 
            # imgContour = imgResult.copy()
            # =============================================================================

            imgGray = cv2.cvtColor(imgResult, cv2.COLOR_BGR2GRAY)
            #sigma, the higher the value, the more blur you get
            imgBlur = cv2.GaussianBlur(imgGray,(7,7),1)

            (cnts, _) = cv2.findContours(imgBlur, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE) 
            #contours = sorted(cnts, key=cv2.contourArea, reverse=False)
            print(contours[0])
        #    idx = 0 

            for c in cnts: 

                area = cv2.contourArea(c)
                if area > 1000:
                    x,y,w,h = cv2.boundingRect(c) 
                    if w>400 and h>400:
                        idx+=1 
                        new_img=imgResult[y:y+h,x:x+w] 
                        #print('banana_images/N/' +day + '/'+ num + '.png')
                        cv2.imwrite('banana_images/B/' +day + '/'+ num + '.png', new_img) 

act1.jpg
ac
[[[1219 1398]]

 [[1217 1400]]

 [[1221 1400]]]
check2
check3
7.0
check3
58.0
check3
17.5
check3
219.0
check3
47.5
check3
25.0
check3
25.0
check3
22.0
check3
39.0
check3
18.0
check3
14.0
check3
39.0
check3
64.0
check3
3540.5
check3
32.0
check3
14.0
check3
841.5
check3
393.0
check3
20.0
check3
301.5
check3
189.0
check3
168.0
check3
418.0
check3
581.5
check3
182.0
check3
294.0
check3
298.5
check3
14.0
check3
14.0
check3
14.0
check3
16.0
check3
20.0
check3
14.0
check3
398.5
check3
263.0
check3
14.0
check3
523.0
check3
41.0
check3
24.5
check3
1287.0
check3
31.5
check3
14.0
check3
43.0
check3
14.0
check3
39.5
check3
93.0
check3
24.0
check3
16.0
check3
30.0
check3
14.0
check3
22.0
check3
83.0
check3
52.0
check3
23.0
check3
76.5
check3
25.5
check3
30.0
check3
18.0
check3
68.5
check3
14.0
check3
43.5
check3
14.0
check3
92.0
check3
39.0
check3
45.5
check3
42.0
check3
30.0
check3
29.5
check3
22.0
check3
60.0
check3
18.0
check3
38.0
check3
14.0
check3
14.0
check3
456.5
check3
394.0
ch

[[[1219 1398]]

 [[1217 1400]]

 [[1221 1400]]]
check2
check3
8.0
check3
8.0
check3
53.0
check3
20.0
check3
68.0
check3
26.0
check3
20.0
check3
15.0
check3
16.0
check3
30.0
check3
22.5
check3
30.0
check3
131.0
check3
36.5
check3
19.5
check3
20.0
check3
92.5
check3
389.5
check3
260.5
check3
300.0
check3
965.0
check3
273.5
check3
77.5
check3
51.0
check3
50.5
check3
95.5
check3
538.0
check3
470.5
check3
518.0
check3
25.0
check3
284.5
check3
30.5
check3
134.0
check3
23.5
check3
18.0
check3
136.0
check3
133.5
check3
116.0
check3
300.5
check3
470.0
check3
79.0
check3
236.0
check3
258.5
check3
285.0
check3
30.0
check3
57.0
check3
110.0
check3
209.0
check3
484.5
check3
75.0
check3
358.0
check3
533.5
check3
4706.0
check3
60.0
check3
1434.5
check3
116.0
check3
184.5
check3
20.0
check3
238.0
check3
103.5
check3
211.0
check3
93.0
check3
402.0
check3
1207.0
check3
93.0
check3
309.5
check3
974.5
check3
156.5
check3
564.0
check3
14.0
check3
310.0
check3
20.0
check3
187.0
check3
32.0
check3
396.0
chec

[[[1219 1398]]

 [[1217 1400]]

 [[1221 1400]]]
check2
check3
8.0
check3
10.0
check3
12.0
check3
11.0
check3
136.0
check3
27.5
check3
15.0
check3
84.5
check3
173.5
check3
22.0
check3
14.0
check3
309.5
check3
297.5
check3
123.0
check3
94.5
check3
30.0
check3
1163.5
check3
22.0
check3
207.0
check3
44.5
check3
609.0
check3
45.0
check3
44.5
check3
321.0
check3
23.0
check3
31.5
check3
20.0
check3
469.5
check3
1263.5
check3
200.0
check3
22.0
check3
4276.0
check3
101.5
check3
561.0
check3
124.0
check3
67.0
check3
14.0
check3
73.5
check3
115.5
check3
191.5
check3
538.5
check3
18.0
check3
341.0
check3
1769.0
check3
262.5
check3
51.0
check3
411.0
check3
62.0
check3
65.5
check3
105.5
check3
20.0
check3
312.0
check3
143.0
check3
968.5
check3
37.5
check3
1754.0
check3
471.0
check3
186.0
check3
596.0
check3
1609.0
check3
154.5
check3
259.0
check3
245.5
check3
62.5
check3
35.0
check3
25.0
check3
53.0
check3
151.5
check3
535.5
check3
155.0
check3
203.5
check3
173.5
check3
872.5
check3
427.0
check3
30.

check3
14.0
check3
300.5
check3
21.5
check3
25.0
check3
21.5
check3
530.0
check3
51.5
check3
14.0
check3
37.5
check3
29.0
check3
28.0
check3
62.0
check3
41.0
check3
14.0
check3
59.5
check3
8.0
check3
55.5
check3
45.5
check3
32.0
check3
234.0
check3
18.0
check3
39.0
check3
8.0
check3
40.0
check3
14.0
check3
26.0
check3
22.0
check3
8.0
check3
17.0
check3
79.5
check3
26.5
check3
267.5
check3
84.0
check3
3005583.0
check4
check3
18.0
check3
18.0
check3
11.0
check3
57.0
check3
14.0
check3
8.0
check3
101.0
check3
43.0
check3
8.0
check3
52.5
check3
35.0
bct1.jpg
bc
[[[1219 1398]]

 [[1217 1400]]

 [[1221 1400]]]
check2
check3
7.0
check3
7.0
check3
11.0
check3
12.5
check3
11.0
check3
12.5
check3
197.5
check3
22.5
check3
14.0
check3
21.5
check3
18.0
check3
14.0
check3
61.5
check3
14.0
check3
37.5
check3
14.0
check3
405.5
check3
37.0
check3
76.0
check3
37.0
check3
30.0
check3
18.0
check3
60.0
check3
331.0
check3
18.0
check3
55.0
check3
21.5
check3
140.0
check3
22.0
check3
26.5
check3
498.0
check3

[[[1219 1398]]

 [[1217 1400]]

 [[1221 1400]]]
check2
check3
8.0
check3
8.0
check3
10.0
check3
47.0
check3
12.0
check3
13.0
check3
15.5
check3
72.0
check3
85.0
check3
16.0
check3
75.5
check3
72.0
check3
72.0
check3
22.0
check3
57.0
check3
103.5
check3
128.5
check3
42.0
check3
83.5
check3
695.0
check3
211.0
check3
156.5
check3
361.5
check3
136.5
check3
24.0
check3
16.0
check3
19.0
check3
232.5
check3
2376.5
check3
750.5
check3
344.0
check3
52.0
check3
1366.0
check3
2208.5
check3
166.0
check3
38.0
check3
235.0
check3
97.0
check3
86.5
check3
301.0
check3
30.0
check3
24.0
check3
153.0
check3
100.5
check3
44.0
check3
211.0
check3
28.0
check3
339.0
check3
18.0
check3
731.0
check3
29.5
check3
26.0
check3
607.0
check3
828.5
check3
20.0
check3
176.5
check3
1012.5
check3
715.0
check3
21468.5
check3
351.5
check3
18.0
check3
18.0
check3
14.0
check3
20.0
check3
189.5
check3
34.0
check3
116.0
check3
127.0
check3
64.0
check3
206.5
check3
23.0
check3
686.5
check3
1253.5
check3
28.0
check3
138.5
check

check3
23.0
check3
160.0
check3
136.0
check3
180.0
check3
1255.5
check3
53.0
check3
118.0
check3
22.0
check3
90.0
check3
116.0
check3
100.0
check3
400.0
check3
63.0
check3
1337.0
check3
1093.0
check3
107.0
check3
42.0
check3
329.0
check3
188.0
check3
137.0
check3
120.5
check3
718.5
check3
93.5
check3
432.5
check3
518.0
check3
4895.0
check3
164.0
check3
102.0
act2.jpg
ac
[[[1219 1398]]

 [[1217 1400]]

 [[1221 1400]]]
check2
check3
7.0
check3
130.5
check3
36.0
check3
18.0
check3
18.0
check3
37.0
check3
14.0
check3
14.0
check3
14.0
check3
14.0
check3
14.0
check3
334.5
check3
634.5
check3
311.5
check3
159.0
check3
417.0
check3
148.0
check3
221.5
check3
193.5
check3
40.0
check3
642.5
check3
169.5
check3
126.5
check3
57.0
check3
187.0
check3
20.0
check3
32.0
check3
321.0
check3
37.5
check3
32.0
check3
24.0
check3
127.5
check3
24.5
check3
20.0
check3
16.0
check3
24.5
check3
16.0
check3
35.0
check3
16.0
check3
30.5
check3
38.5
check3
34.0
check3
16.0
check3
22.0
check3
16.0
check3
35.0
check3

[[[1219 1398]]

 [[1217 1400]]

 [[1221 1400]]]
check2
check3
21.0
check3
8.0
check3
7.0
check3
41.0
check3
14.5
check3
11.0
check3
13.0
check3
12.0
check3
31.0
check3
40.0
check3
32.0
check3
52.0
check3
45.0
check3
108.0
check3
176.0
check3
101.0
check3
20.0
check3
235.0
check3
27.5
check3
77.5
check3
46.0
check3
111.5
check3
315.0
check3
923.5
check3
325.5
check3
377.5
check3
115.0
check3
89.0
check3
50.0
check3
51.0
check3
60.0
check3
62.0
check3
137.0
check3
25.0
check3
22.0
check3
20.0
check3
229.0
check3
106.5
check3
252.5
check3
91.0
check3
880.5
check3
168.0
check3
332.0
check3
14.0
check3
14.0
check3
90.0
check3
38.5
check3
33.5
check3
86.5
check3
36.0
check3
14.0
check3
178.0
check3
36.0
check3
25.0
check3
32.0
check3
408.0
check3
14.0
check3
14.0
check3
22.0
check3
72.5
check3
160.0
check3
14.0
check3
28.0
check3
32.0
check3
117.0
check3
142.0
check3
44.0
check3
30.0
check3
54.0
check3
240.5
check3
42.0
check3
264.5
check3
84.0
check3
50.0
check3
18.0
check3
14.0
check3
806.

655.5
check3
33.0
check3
30.0
check3
575.5
check3
16.0
check3
83.0
check3
16.0
check3
71.5
check3
133.5
check3
36.0
check3
66.0
check3
26.0
check3
29.0
check3
28.5
check3
16.0
check3
33.0
check3
16.0
check3
1516.5
check3
82.0
check3
386.0
check3
48.5
check3
33.0
check3
42.5
check3
64.5
check3
14.0
check3
59.5
check3
386.5
check3
151.0
check3
61.5
check3
27.0
check3
201.0
check3
32.0
check3
36.5
check3
23.0
check3
50.5
check3
16.0
check3
36.5
check3
33.0
check3
170.0
check3
18.0
check3
528.0
check3
120.5
check3
42.0
check3
256.0
check3
201.5
check3
18.0
check3
1381.5
check3
29.0
check3
39.0
check3
215.5
check3
20.5
check3
44.0
check3
25.5
check3
37.5
check3
16.0
check3
92.5
check3
43.5
check3
18.0
check3
14.0
check3
24.0
check3
20.0
check3
80.0
check3
14.0
check3
22.0
check3
66.0
check3
47.0
check3
14.0
check3
9334.5
check3
32.0
check3
30.0
check3
14.0
check3
32.0
check3
225.5
check3
16.0
check3
66.0
check3
417.5
check3
57.0
check3
18.0
check3
1088.0
check3
68.0
check3
201.0
check3
18.0

16.0
check3
295.0
check3
99.0
check3
26.0
check3
721.0
check3
195.5
check3
29.5
check3
1190.5
check3
1142.5
check3
303.5
check3
165.5
check3
23.0
check3
60.0
check3
2233.0
check3
3944.0
check3
34.0
check3
1187.5
check3
110.0
check3
175.0
check3
255.0
check3
14.0
check3
76.0
check3
117.0
check3
18.0
check3
14.0
check3
14.0
check3
280.0
check3
47.0
check3
205.5
check3
122522.0
check3
14.0
check3
160.0
check3
115.0
check3
2381.0
check3
294.0
check3
340.5
check3
396.0
check3
147.5
check3
143.0
check3
369.0
check3
33.0
check3
112.0
check3
87.5
check3
33.0
check3
74.0
check3
202.0
check3
579.0
check3
163.5
check3
1913.5
check3
120.0
check3
1396.5
check3
196.0
check3
359.0
check3
131.0
check3
271.0
check3
215.5
check3
307.0
check3
258.5
check3
70.0
check3
86.5
check3
80.5
check3
423.0
check3
129.5
check3
22.0
check3
1978.0
check3
193.0
check3
161.0
check3
207.5
check3
23.0
check3
34.0
check3
74.0
check3
415.5
check3
14.0
check3
138.0
check3
337.0
check3
156.0
check3
34.0
check3
4332.5
check3


check3
55.5
check3
90.5
check3
723.5
check3
28.0
check3
22.0
check3
14.0
check3
8.0
check3
261.5
check3
22.0
check3
18.0
check3
14.0
check3
87.0
check3
21.5
check3
30.0
check3
14.0
check3
18.0
check3
977.0
check3
93.0
check3
194.0
check3
33.0
check3
100.0
check3
28.5
check3
50.0
check3
16.0
check3
22.0
check3
380.5
check3
397.0
check3
46.0
check3
150.0
check3
30.0
check3
20.0
check3
115.0
check3
136.5
check3
18.0
check3
14.0
check3
91.5
check3
20.0
check3
14.0
check3
170.0
check3
20.0
check3
20.0
check3
14.0
check3
96.0
check3
14.0
check3
36.5
check3
29.0
check3
20.0
check3
137.0
check3
20.0
check3
73.0
check3
71.0
check3
233.5
check3
592.0
check3
646.5
check3
267.5
check3
142.5
check3
43.0
check3
183.0
check3
52.5
check3
183.5
act3.jpg
ac
[[[1219 1398]]

 [[1217 1400]]

 [[1221 1400]]]
check2
check3
7.0
check3
14.0
check3
23.0
check3
40.0
check3
19.0
check3
37.5
check3
104.0
check3
51.0
check3
54.5
check3
80.0
check3
52.0
check3
36.5
check3
37.0
check3
25.0
check3
404.5
check3
116.0
c

check3
32.0
check3
149.0
check3
44.0
check3
25.0
check3
35.0
check3
91.0
check3
210.0
check3
390.5
check3
531.5
check3
216.0
check3
28.0
check3
14271.0
check3
63.5
check3
98.0
check3
69045.5
check3
5505.5
check3
106.5
check3
465.5
check3
84.0
check3
163.0
s3t3.jpg
s3
[[[1219 1398]]

 [[1217 1400]]

 [[1221 1400]]]
check2
check3
7.0
check3
32.0
check3
16.0
check3
16.0
check3
24.0
check3
120.0
check3
66.0
check3
72.0
check3
72.0
check3
248.0
check3
19.0
check3
64.0
check3
134.5
check3
508.5
check3
115.5
check3
29.0
check3
116.5
check3
140.5
check3
65.5
check3
279.0
check3
51.5
check3
82.5
check3
271.5
check3
319.5
check3
154.5
check3
186.5
check3
119.5
check3
109.0
check3
93.5
check3
369.5
check3
33.0
check3
240.5
check3
62.5
check3
474.0
check3
136.0
check3
200.0
check3
77.0
check3
107.0
check3
381.5
check3
126.5
check3
113.0
check3
38.0
check3
81.5
check3
1241.5
check3
35.0
check3
14.0
check3
20.0
check3
241.5
check3
146.0
check3
53.0
check3
45.0
check3
39.0
check3
307.5
check3
57.0
ch

check3
14.0
check3
21.5
check3
14.0
check3
14.0
check3
49.5
check3
57.5
check3
14.0
check3
64.5
check3
37.5
check3
173.0
check3
14.0
check3
14.0
check3
38.5
check3
14.0
check3
14.0
check3
33.5
check3
49.5
check3
56.0
check3
49.5
check3
22.0
check3
199.5
check3
68.5
check3
18.0
check3
14.0
check3
14.0
check3
14.0
check3
26.0
check3
34.5
check3
40.0
check3
21.5
check3
78.0
check3
57.0
check3
1015.0
check3
14.0
check3
1937.5
check3
84.5
check3
16.0
check3
25.5
check3
24.5
check3
118.5
check3
210.0
check3
39.0
check3
81.5
check3
26.5
check3
200.0
check3
46.5
check3
264.0
check3
132.5
check3
80.0
check3
113.5
check3
69.0
check3
32.0
check3
107.0
check3
14.0
check3
39.0
check3
23.0
check3
291.0
check3
83.5
check3
14.0
check3
32.5
check3
14.0
check3
30.0
check3
22.0
check3
25.5
check3
191.0
check3
45.5
check3
31.5
check3
210.0
check3
26.0
check3
310.0
check3
192.0
check3
185.5
check3
28.0
check3
156.0
check3
14.0
check3
117.5
check3
14.0
check3
14.0
check3
14.0
check3
16.0
check3
39.5
check3


check3
26.5
check3
34.5
check3
168.5
check3
22.0
check3
50.5
check3
106.5
check3
23.0
check3
37.5
check3
227.0
check3
14.0
check3
26.0
check3
18.0
check3
14.0
check3
21.5
check3
18.0
check3
213.0
check3
14.0
check3
27.5
check3
58.0
check3
97.0
check3
58.5
check3
102.5
check3
305.5
check3
69.0
check3
14.0
check3
14.0
check3
14.0
check3
74.5
check3
23.0
check3
38.0
check3
14.0
check3
14.0
check3
53.0
check3
63.0
check3
70.5
check3
26.5
check3
37.5
check3
14.0
check3
46.5
check3
18.0
check3
209.0
check3
28.0
check3
14.0
check3
14.0
check3
14.0
check3
14.0
check3
14.0
check3
33.5
check3
41.0
check3
14.0
check3
104.5
check3
46.5
check3
21.5
check3
38.0
check3
263.0
check3
39.0
check3
14.0
check3
111.5
check3
14.0
check3
51.0
check3
50.0
check3
48.0
check3
30.0
check3
125.5
check3
49.5
check3
14.0
check3
67.0
check3
11.0
check3
69.5
check3
29.0
check3
116.5
check3
14.0
check3
43.0
check3
346.5
check3
14.0
check3
14.0
check3
34.0
check3
116.5
check3
18.0
check3
30.0
check3
461.5
check3
186.5


check3
876.5
check3
231.5
check3
14.0
check3
30.0
check3
29.5
check3
24.0
check3
41.0
check3
14.0
check3
33.0
check3
20.0
check3
14.0
check3
114.0
check3
14.0
check3
14.5
check3
124.0
check3
25.0
check3
21.5
check3
35.0
check3
31.0
check3
14.0
check3
14.0
check3
76.5
check3
16.0
check3
97.5
check3
18.0
check3
14.0
check3
49.5
check3
27.5
check3
75.0
check3
1365474.5
check4
check3
150.5
check3
446.5
check3
32.0
check3
102.5
check3
21.5
check3
14.0
check3
34.0
check3
116.0
check3
25.5
check3
44.0
check3
545.0
check3
14.0
check3
74.0
check3
18.0
check3
122.0
check3
14.0
check3
14.0
check3
18.0
check3
53.0
check3
48.5
check3
120.5
check3
14.0
check3
14.0
check3
77.0
check3
14.0
check3
54.0
check3
50.0
check3
611.0
check3
26.0
check3
233.0
check3
106.0
check3
28.0
check3
315.5
check3
48.5
check3
126.0
check3
18.0
check3
31.5
check3
18.0
check3
30.0
check3
168.5
check3
67.0
check3
26.5
check3
47.0
check3
154.0
check3
2481.0
check3
33.0
check3
22.0
check3
461.0
check3
14.0
check3
114.5
check3

check3
14.0
check3
58.5
check3
47.0
check3
145.0
check3
47.0
check3
18.0
check3
33.5
check3
33.0
check3
14.0
check3
18.0
check3
156.5
check3
74.0
check3
21.5
check3
58.0
check3
46.0
check3
18.0
check3
14.0
check3
18.0
check3
67.5
check3
68.0
check3
79.5
check3
18.0
check3
52.0
check3
115.0
check3
173.5
check3
76.0
check3
24.0
check3
18.0
check3
60.0
check3
65.0
check3
86.0
check3
35.5
check3
43.0
check3
8.0
check3
28.0
check3
181.0
check3
25.0
check3
980.0
check3
146.0
check3
14.0
check3
25.0
check3
29.0
check3
199.0
check3
14.0
check3
53.0
check3
276.0
check3
97.0
check3
126.0
check3
64.0
check3
1056.0
check3
41.0
check3
134.0
check3
41.0
check3
24.5
check3
102.5
check3
16.0
check3
39.0
check3
116.0
check3
39.0
check3
23.0
check3
544.5
check3
22.0
check3
81.0
check3
133.0
check3
200.0
check3
4061.0
check3
42.0
check3
33.5
check3
191.0
check3
352.0
check3
48.5
check3
81.0
check3
202.0
check3
516.0
check3
28.0
check3
39.0
check3
49.5
check3
34.0
check3
23.5
check3
101.0
check3
56.0
chec

[[[1219 1398]]

 [[1217 1400]]

 [[1221 1400]]]
check2
check3
25.0
check3
56.0
check3
14.0
check3
14.0
check3
90.5
check3
30.5
check3
178.5
check3
30.0
check3
80.0
check3
25.0
check3
76.5
check3
103.0
check3
22.0
check3
38.0
check3
736.5
check3
149.5
check3
75.5
check3
302.5
check3
14.0
check3
38.0
check3
75.0
check3
1002.5
check3
827.5
check3
18.0
check3
20.0
check3
941.0
check3
23.0
check3
14.0
check3
14.0
check3
14.0
check3
14.0
check3
14.0
check3
1243.5
check3
63.0
check3
42.0
check3
18.0
check3
41.5
check3
14.0
check3
1107.0
check3
331.5
check3
18.0
check3
14.0
check3
14.0
check3
68.5
check3
209.0
check3
148.5
check3
49.0
check3
693.5
check3
179.0
check3
272.0
check3
193.0
check3
229.0
check3
20.0
check3
165.0
check3
39.0
check3
52.5
check3
20.0
check3
1244.0
check3
747.5
check3
83.0
check3
36.0
check3
801.5
check3
14.0
check3
248.0
check3
83.5
check3
84.0
check3
97.5
check3
14.0
check3
42.5
check3
78.5
check3
30.0
check3
219.5
check3
3105.5
check3
16.0
check3
104.0
check3
121.5
c

check3
14.0
check3
33.0
check3
14.0
check3
42.0
check3
122.0
check3
33.0
check3
59.0
check3
7.0
check3
36.0
check3
25.0
check3
18.0
check3
14.0
check3
18.0
check3
14.0
check3
56.5
check3
22.0
check3
150.5
check3
26.0
check3
18.0
check3
30.0
check3
319.0
check3
420.0
check3
107.0
check3
14.0
check3
66.0
check3
23.0
check3
174.5
check3
1312.0
check3
26.0
check3
93.0
check3
28.0
check3
14.0
check3
14.0
check3
93.5
check3
152.0
check3
38.0
check3
951.5
check3
165.0
check3
219.5
check3
29.0
check3
31.0
check3
39.5
check3
14.0
check3
94.0
check3
15.0
check3
95.0
check3
433.0
check3
14.0
check3
25.0
check3
27.0
check3
260.5
check3
46.0
check3
244.0
check3
14.0
check3
2898.0
check3
74.5
check3
174.0
check3
575.0
check3
22.0
check3
14.0
check3
25.5
check3
66.0
check3
251.0
check3
105.5
check3
98.0
check3
57.5
check3
173.5
check3
101.0
check3
38.0
check3
20.0
check3
14.0
check3
18.0
check3
300.5
check3
14.0
check3
14.0
check3
26.5
check3
14.0
check3
219.5
check3
42.0
check3
18.0
check3
56.0
chec

[[[1219 1398]]

 [[1217 1400]]

 [[1221 1400]]]
check2
check3
8.0
check3
62.0
check3
20.5
check3
11.0
check3
21.5
check3
12.0
check3
15.0
check3
13.0
check3
13.0
check3
18.5
check3
72.0
check3
144.0
check3
132.0
check3
28.0
check3
19.5
check3
34.5
check3
37.5
check3
87.5
check3
183.5
check3
404.0
check3
102.0
check3
98.5
check3
298.0
check3
162.0
check3
54.0
check3
54.0
check3
110.0
check3
389.5
check3
108.0
check3
108.0
check3
51.5
check3
14.0
check3
307.0
check3
25.0
check3
25.0
check3
53.0
check3
37.5
check3
41.5
check3
208.0
check3
12.0
check3
171.5
check3
301.5
check3
47.0
check3
474.0
check3
36.0
check3
106.5
check3
60.0
check3
97.5
check3
277.0
check3
340.5
check3
25.0
check3
82.5
check3
125.5
check3
26.0
check3
56.5
check3
204.5
check3
25.0
check3
121.0
check3
22.0
check3
159.0
check3
242.0
check3
151.5
check3
26.0
check3
22.0
check3
222.0
check3
117.0
check3
34.0
check3
23.0
check3
147.5
check3
27.0
check3
202.5
check3
700.0
check3
19.0
check3
1887.0
check3
60.0
check3
14.0
ch

check3
60.0
check3
32.5
check3
50.0
check3
101.0
check3
65.5
check3
42.0
check3
95.0
check3
20.0
check3
22.5
check3
145.5
check3
285.5
check3
23.0
check3
44.0
check3
138.5
check3
46.5
check3
56.0
check3
48.5
check3
107.0
check3
31.5
check3
34.0
check3
63.0
check3
29.0
check3
93.5
check3
33.0
check3
113.0
check3
32.5
check3
35.0
check3
34.5
check3
194.0
check3
14.0
check3
37.0
check3
8.0
check3
1056.5
check3
346.0
check3
108.0
check3
180.5
check3
15.5
check3
102.0
check3
89.0
check3
48.0
s2t4.jpg
s2
[[[1219 1398]]

 [[1217 1400]]

 [[1221 1400]]]
check2
check3
7.0
check3
10.0
check3
53.0
check3
14.0
check3
15.0
check3
58.0
check3
22.0
check3
112.0
check3
75.0
check3
96.0
check3
97.0
check3
68.0
check3
68.0
check3
68.0
check3
113.5
check3
115.0
check3
50.5
check3
212.5
check3
46.0
check3
220.5
check3
54.5
check3
169.5
check3
152.0
check3
89.5
check3
438.5
check3
25.5
check3
425.0
check3
88.0
check3
41.5
check3
1215.5
check3
54.0
check3
72.0
check3
18.0
check3
25.0
check3
57.0
check3
389.

[[[1219 1398]]

 [[1217 1400]]

 [[1221 1400]]]
check2
check3
13.0
check3
7.0
check3
11.0
check3
21.5
check3
377.0
check3
14.0
check3
46.0
check3
61.0
check3
26.0
check3
22.0
check3
95.5
check3
38.0
check3
22.0
check3
14.0
check3
14.0
check3
18.0
check3
28.5
check3
138.5
check3
18.0
check3
31.0
check3
23.0
check3
182.5
check3
25.0
check3
23.0
check3
18.0
check3
21.5
check3
54.5
check3
14.0
check3
222.0
check3
8.0
check3
42.0
check3
43.0
check3
53.5
check3
44.0
check3
70.5
check3
242.5
check3
124.0
check3
14.0
check3
24.5
check3
54.5
check3
20.0
check3
44.0
check3
23.0
check3
35.0
check3
24.0
check3
8.0
check3
14.0
check3
8.0
check3
593.0
check3
18.0
check3
28.5
check3
8.0
check3
14.0
check3
79.5
check3
89.0
check3
88.5
check3
18.0
check3
352.0
check3
39.0
check3
14.0
check3
14.0
check3
14.0
check3
8.0
check3
23.0
check3
14.0
check3
20.0
check3
14.0
check3
368.0
check3
14.0
check3
66.5
check3
41.5
check3
53.0
check3
160.5
check3
30.0
check3
72.5
check3
39.5
check3
147.5
check3
14.0
chec

588185.0
check4
check3
143.0
check3
61.5
check3
37.5
check3
14.0
check3
419.5
check3
47.0
check3
14.0
check3
80.0
check3
431.0
check3
62.0
check3
45.0
check3
45.0
check3
366.0
check3
25.0
check3
2342.5
check3
45.5
check3
60.0
check3
265.0
check3
18.0
check3
481.0
check3
289.5
check3
12065.5
check3
184.0
check3
14.0
check3
277.0
check3
50.0
check3
20.0
check3
18.0
check3
264.5
check3
42.0
check3
120.0
check3
300.0
check3
585.0
check3
55.5
check3
132.5
check3
84.0
check3
301.5
check3
157.5
check3
23.5
check3
333.0
check3
90.0
check3
26.0
check3
86.5
check3
37.5
check3
14.0
check3
14.0
check3
14.0
check3
1079.5
check3
248.5
check3
45.0
check3
63.5
check3
69.0
check3
142.5
check3
79.0
check3
79.0
check3
25.0
check3
33.5
check3
1728.0
check3
176.5
check3
14.0
check3
666.5
check3
2351.0
check3
83.0
check3
100.5
check3
25.0
check3
207.0
check3
136.5
check3
119.5
check3
1149.5
check3
43.0
check3
2675.5
check3
49.0
check3
60.0
check3
34.0
check3
88.0
check3
76.5
check3
14.0
check3
14.0
check3
2

check3
212.5
check3
41.5
check3
49.5
check3
28.0
check3
618.0
check3
18.0
check3
18.0
check3
21.5
check3
57.5
check3
8.0
check3
46.0
check3
138.0
check3
14.0
check3
67.5
check3
121.0
check3
26.5
check3
14.0
check3
397.0
check3
115.0
check3
36.0
check3
14.0
check3
119.0
check3
14.0
check3
18.0
check3
14.0
check3
274.5
check3
117.5
check3
133.5
check3
18.0
check3
137.5
check3
54.0
check3
29.0
check3
18.0
check3
46.5
check3
43.5
check3
25.0
check3
65.5
check3
39.5
check3
22.0
check3
26.5
check3
72.5
check3
189.0
check3
14.0
check3
20.0
check3
108.5
check3
296.0
check3
14.0
check3
18.0
check3
18.0
check3
88.5
check3
28.0
check3
28.0
check3
14.0
check3
21.5
check3
14.0
check3
14.0
check3
18.0
check3
14.0
check3
479.0
check3
79.0
check3
21.5
check3
18.0
check3
201.5
check3
14.0
check3
14.0
check3
24.0
check3
18.0
check3
14.0
check3
1961.0
check3
14.0
check3
76.0
check3
104.5
check3
136.0
check3
79.0
check3
24.0
check3
31.5
check3
44.5
check3
1769.0
check3
18.0
check3
14.0
check3
27.5
check3


125937.5
check3
57.0
check3
227.0
check3
201.5
check3
8899.0
check3
509.0
check3
658.5
check3
44.0
check3
14.0
check3
288.5
check3
48.0
check3
621.5
check3
657.0
check3
3342.0
check3
261.5
check3
246.5
check3
112.0
check3
43.0
check3
312.0
check3
24.0
check3
148.5
check3
16.0
check3
1142.0
check3
46.0
check3
264.5
check3
32.0
check3
16.0
check3
14.0
check3
39.0
check3
222.0
check3
154.0
check3
880.5
check3
293.0
check3
54.0
check3
16.0
check3
24.0
check3
88.0
check3
16.0
check3
22.0
check3
79.0
check3
27.0
check3
22.0
check3
503.0
check3
16.0
check3
481.0
check3
32.5
check3
11955.5
check3
22.0
check3
433.0
check3
39.0
check3
182.0
check3
14.0
check3
56.0
check3
28.5
check3
21.5
check3
518.5
check3
78.0
check3
632.5
check3
48.0
check3
859.0
check3
14.0
check3
18.0
check3
1247.5
check3
30.0
check3
68.0
check3
111.5
check3
82.5
check3
14.0
check3
69.0
check3
296.0
check3
272.0
check3
44.0
check3
51.5
check3
77.0
check3
914.0
check3
61.0
check3
34.0
check3
88.0
check3
206.0
check3
1630.5
c

check3
33.0
check3
198.0
check3
79.0
check3
1373.0
check3
33.0
check3
1362.0
check3
23.0
check3
24.0
check3
548.5
check3
26.0
check3
38.0
check3
18.0
check3
91.5
check3
42.5
check3
14.0
check3
114.5
check3
21.5
check3
448.0
check3
465.5
check3
41.5
check3
134.5
check3
980.5
check3
106.5
check3
45.5
check3
33.0
check3
240.5
check3
27.0
check3
20.0
check3
14.0
check3
47.0
check3
14.0
check3
63.0
check3
286.0
check3
323.5
check3
182.0
check3
14.0
check3
18.0
check3
18.0
check3
44.0
check3
37.5
check3
72.5
check3
119.5
check3
14.0
check3
290.5
check3
43.0
check3
14.0
check3
53.5
check3
58.0
check3
14.0
check3
46.5
check3
51.5
check3
26.0
check3
117.5
check3
54.0
check3
97.0
check3
267.0
check3
53.0
check3
30.0
check3
14.0
check3
26.5
check3
25.0
check3
21.5
check3
14.0
check3
20.0
check3
620.0
check3
29.0
check3
18.0
check3
22.0
check3
14.0
check3
45.0
check3
18.0
check3
14.0
check3
14.0
check3
57.5
check3
84.0
check3
18.0
check3
242.5
check3
26.5
check3
14.0
check3
91.5
check3
32.0
check3

check3
824.5
check3
14.0
check3
38.5
check3
664.5
check3
14.0
check3
70.0
check3
43.5
check3
16.0
check3
210.5
check3
107.5
check3
20.0
check3
65.5
check3
32.5
check3
14.0
check3
49.5
check3
14.0
check3
50.0
check3
155.0
check3
45.0
check3
286.5
check3
47.0
check3
50.0
check3
32.0
check3
31.0
check3
14.0
check3
215.0
check3
542.0
check3
52.0
check3
35.0
check3
56.0
check3
34.5
check3
133.0
check3
22.0
check3
16.0
check3
64.0
check3
47.0
check3
77.0
check3
16.0
check3
14.0
check3
20.0
check3
20.0
check3
14.0
check3
29.0
check3
24.5
check3
14.0
check3
16.0
check3
16.0
check3
43.5
check3
24.5
check3
24.0
check3
32.0
check3
68.0
check3
91.5
check3
105.5
check3
26.0
check3
142.0
check3
78.5
check3
20.0
check3
48.0
check3
21.5
check3
28.0
check3
118.0
check3
16.0
check3
78.0
check3
18.0
check3
81.0
check3
16.0
check3
16.0
check3
26.0
check3
40.0
check3
26.0
check3
18.0
check3
66.0
check3
14.0
check3
64.0
check3
45.0
check3
347.5
check3
18.0
check3
877.0
check3
116.0
check3
62.0
check3
48.0
c

416.5
check3
54.0
check3
20.0
check3
30.0
check3
65.0
check3
16.0
check3
420.5
check3
69.5
check3
133.5
check3
36.5
check3
36.5
check3
16.0
check3
862.5
check3
82.0
check3
79.5
check3
92.0
check3
27.5
check3
121.0
check3
16.0
check3
128.5
check3
176.5
check3
30.0
check3
58.0
check3
901.0
check3
5307.5
check3
165.0
check3
45.5
check3
14.0
check3
16.0
check3
31.5
check3
46.5
check3
43.0
check3
16.0
check3
997.0
check3
298.0
check3
48.0
check3
16.0
check3
28.5
check3
16.0
check3
53.5
check3
18.0
check3
20.0
check3
24.0
check3
190.5
check3
16.0
check3
39.5
check3
16.0
check3
20.0
check3
199.0
check3
16.0
check3
16.0
check3
520.5
check3
16.0
check3
124.0
check3
16.0
check3
18.0
check3
39.5
check3
16.0
check3
34.0
check3
43.0
check3
1151.0
check3
28.5
check3
48.0
check3
16.0
check3
360.5
check3
80.5
check3
28.0
check3
24.0
check3
36.5
check3
86.0
check3
61.5
check3
24.0
check3
14.0
check3
71.0
check3
16.0
check3
14.0
check3
224.0
check3
20.0
check3
16.0
check3
45.5
check3
24.0
check3
6466.0


check3
52.5
check3
24.0
check3
36.0
check3
16.0
check3
165.0
check3
265.0
check3
18.0
check3
456.0
check3
16.0
check3
290.5
check3
18.0
check3
30.0
check3
29.5
check3
24.0
check3
16.0
check3
92.5
check3
421.0
check3
18.0
check3
16.0
check3
18.0
check3
25.5
check3
34.0
check3
32.0
check3
535.5
check3
163.5
check3
388.0
check3
109.5
check3
18.0
check3
14.0
check3
127.0
check3
16.0
check3
30.5
check3
163.5
check3
54.5
check3
18369.0
check3
187.5
check3
14.0
check3
109.5
check3
9879.5
check3
87.0
check3
195.0
check3
14.0
check3
14.0
check3
40.0
check3
14.0
check3
30.0
check3
30.0
check3
28.0
check3
92.5
check3
156.0
check3
16.0
check3
20.0
check3
24.5
check3
130.0
check3
55.0
check3
165.0
check3
63.5
check3
243.5
check3
59.0
check3
211.5
check3
37.0
check3
56.5
check3
14.0
check3
42.5
check3
70.0
check3
480.5
check3
14.0
check3
133.5
check3
87.5
check3
25.0
check3
18.0
check3
597.0
check3
22.0
check3
1203.5
check3
38.0
check3
272.5
check3
60.0
check3
24.0
check3
66.5
check3
14.0
check3
11.

check3
196.5
check3
351.5
check3
90.5
check3
38.0
check3
20.0
check3
23.0
check3
28.0
check3
180.0
check3
57.5
check3
18.0
check3
41.0
check3
183.5
check3
14.0
check3
58.0
check3
26.0
check3
53.0
check3
36.0
check3
794.5
check3
53.0
check3
14.0
check3
61.5
check3
24.0
check3
18.0
check3
35.0
check3
61.0
check3
195.0
check3
60.0
check3
66.0
check3
20.0
check3
14.0
check3
907.0
check3
29.5
check3
109.0
check3
198.0
check3
32.0
check3
38.0
check3
65.5
check3
118.0
check3
28.0
check3
36.0
check3
43.5
check3
3579.0
check3
37.5
check3
21.5
check3
36.0
check3
48.5
check3
68.0
check3
125.0
check3
14.0
check3
18.0
check3
14.0
check3
18.0
check3
174.0
check3
92.5
check3
39.5
check3
14.0
check3
74.0
check3
608.0
check3
29.0
check3
47.0
check3
39.5
check3
373.0
check3
18.0
check3
39.0
check3
114.5
check3
18.0
check3
47.0
check3
982.0
check3
94.0
check3
18.0
check3
43.5
check3
90.0
check3
222.5
check3
179.5
check3
212.5
check3
21.5
check3
18.0
check3
35.0
check3
39.0
check3
26.0
check3
180.5
check3

check3
14.0
check3
14.0
check3
51.0
check3
43.0
check3
18.0
check3
21.5
check3
173.5
check3
39.0
check3
41.5
check3
37.5
check3
14.0
check3
37.5
check3
23.0
check3
63.0
check3
151.5
check3
53.0
check3
14.0
check3
368.5
check3
93.0
check3
69.5
check3
14.0
check3
531.5
check3
38.0
check3
23.0
check3
78.0
check3
100.0
check3
14.0
check3
28.0
check3
90.0
check3
26.0
check3
33.0
check3
48.0
check3
62.0
check3
543.5
check3
83.0
check3
43.0
check3
47.0
check3
51.0
check3
201.5
check3
124.0
check3
30.0
check3
14.0
check3
460.0
check3
109.0
check3
79.5
check3
148.0
check3
160.0
check3
269.5
check3
14.0
check3
28.0
check3
458.0
check3
111.0
check3
86.5
check3
33.0
check3
60.0
check3
38.0
check3
33.0
check3
31.5
check3
14.0
check3
257.0
check3
170.0
check3
32.0
check3
62.0
check3
64.0
check3
29.0
check3
53.5
check3
14.0
check3
86.5
check3
14.0
check3
57.0
check3
28.0
check3
28.0
check3
40.0
check3
248.0
check3
23.0
check3
21.5
check3
146.5
check3
49.0
check3
116.5
check3
242.5
check3
30.0
check3


14.0
check3
124.0
check3
65.5
check3
150.5
check3
63.5
check3
166.0
check3
379.5
check3
1554.5
check3
14.0
check3
284.0
check3
42.5
check3
16.0
check3
14.0
check3
247.5
check3
57.0
check3
232.0
check3
765.0
check3
66.0
check3
86.5
check3
151.0
check3
49.0
check3
101.5
check3
33.0
check3
331.0
check3
372.5
check3
23.0
check3
29.0
check3
14.0
check3
14.0
check3
33.0
check3
74.5
check3
67.5
check3
119.5
check3
132.0
check3
23.0
check3
30.5
check3
43.0
check3
252.0
check3
18.0
check3
34.5
check3
129.5
check3
25.5
check3
14.0
check3
26.0
check3
33.0
check3
43.5
check3
33.5
check3
34.5
check3
109.0
check3
22.0
check3
81.0
check3
387.5
check3
130.0
check3
91.0
check3
34.0
check3
14.0
check3
14.0
check3
14.0
check3
14.0
check3
25.0
check3
35.5
check3
138.0
check3
14.0
check3
30.0
check3
16.0
check3
105.0
check3
18.0
check3
66.5
check3
189.5
check3
61.0
check3
74.0
check3
61.0
check3
362.0
check3
59.5
check3
145.5
check3
1110.0
check3
106.0
check3
55.0
check3
14.0
check3
291.5
check3
269.5
chec

[[[1219 1398]]

 [[1217 1400]]

 [[1221 1400]]]
check2
check3
12.0
check3
15.5
check3
43.0
check3
132.0
check3
50.5
check3
30.0
check3
70.5
check3
280.0
check3
74.0
check3
40.0
check3
46.5
check3
176.0
check3
254.5
check3
386.5
check3
116.0
check3
180.0
check3
403.5
check3
98.0
check3
69.0
check3
106.5
check3
484.5
check3
22.0
check3
66.5
check3
527.5
check3
92.5
check3
536.5
check3
196.0
check3
448.0
check3
38.5
check3
52.5
check3
34.5
check3
25.0
check3
25.0
check3
25.0
check3
25.0
check3
246.5
check3
84.5
check3
159.5
check3
262.5
check3
20.0
check3
51.0
check3
137.5
check3
82.0
check3
88.5
check3
25.0
check3
2918.5
check3
37.5
check3
14.0
check3
246.5
check3
249.0
check3
3231.5
check3
14.0
check3
25.0
check3
39.5
check3
101.5
check3
124.0
check3
288.0
check3
435.0
check3
776.0
check3
1087.0
check3
244.5
check3
65.0
check3
20.0
check3
69.5
check3
43.0
check3
209.0
check3
187.5
check3
204.5
check3
112.0
check3
631.0
check3
30.5
check3
123.0
check3
695.5
check3
1447.0
check3
20.0
chec

check3
75.5
check3
18.0
check3
183.5
check3
14.0
check3
18.0
check3
30.0
check3
30.0
check3
146.0
check3
578.0
check3
37.5
check3
127.5
check3
87.0
check3
206.5
check3
181.5
check3
59.5
check3
14.0
check3
308.0
check3
14.0
check3
18.0
check3
28.5
check3
23.5
check3
29.0
check3
346.0
check3
23.5
check3
30.0
check3
37.5
check3
78.0
check3
49.0
check3
681.0
check3
86.5
check3
21.5
check3
26.5
check3
115.0
check3
511.0
check3
14.0
check3
38.0
check3
127.5
check3
14.0
check3
123.5
check3
122.5
check3
14.0
check3
41.0
check3
43.0
check3
40.0
check3
68.0
check3
14.0
check3
14.0
check3
25.0
check3
44.0
check3
264.0
check3
171.0
check3
835.0
check3
155.5
check3
50.0
check3
26.0
check3
14.0
check3
22.0
check3
933.0
check3
31.5
check3
18.0
check3
18.0
check3
14.0
check3
223.0
check3
107.0
check3
58.5
check3
514.0
check3
41.5
check3
160.0
check3
54.5
check3
14.0
check3
252.5
check3
30.5
check3
408.0
check3
14.0
check3
51.0
check3
26.0
check3
60.0
check3
50.0
check3
38.0
check3
34.0
check3
14.0
che

[[[1219 1398]]

 [[1217 1400]]

 [[1221 1400]]]
check2
check3
10.0
check3
20.0
check3
14.0
check3
56.0
check3
12.5
check3
56.0
check3
23.0
check3
39.5
check3
24.0
check3
132.0
check3
130.0
check3
136.0
check3
72.0
check3
50.0
check3
118.0
check3
26.0
check3
24.0
check3
56.0
check3
59.0
check3
195.5
check3
37.5
check3
34.5
check3
73.0
check3
46.5
check3
43.5
check3
350.0
check3
46.5
check3
226.5
check3
382.5
check3
112.0
check3
66.5
check3
227.0
check3
196.5
check3
172.0
check3
67.0
check3
81.0
check3
35.5
check3
22.0
check3
88.5
check3
448.5
check3
253.0
check3
155.5
check3
69.0
check3
734.0
check3
503.0
check3
16.0
check3
159.0
check3
14.0
check3
1696.0
check3
235.0
check3
279.0
check3
40.0
check3
103.0
check3
671.0
check3
185.5
check3
34.0
check3
177.0
check3
114.0
check3
686.5
check3
308.5
check3
72.0
check3
20.0
check3
142.0
check3
77.0
check3
195.0
check3
14.0
check3
147.5
check3
25.0
check3
25.5
check3
16.0
check3
64.0
check3
22.0
check3
20.0
check3
95.0
check3
5309.5
check3
118.

check3
1000.5
check3
110.5
check3
14.0
check3
286.5
check3
439.0
check3
21.5
check3
14.0
check3
14.0
check3
388.0
check3
769.0
check3
27.0
check3
473.0
check3
109.0
check3
69.5
check3
21.5
check3
14.0
check3
23.0
check3
26.0
check3
78.0
check3
32.5
check3
26.0
check3
18.0
check3
22.0
check3
29.0
check3
294.0
check3
50.0
check3
43.0
check3
37.0
check3
14.0
check3
107.5
check3
36.5
check3
54.0
check3
18.0
check3
14.0
check3
14.0
check3
14.0
check3
14.0
check3
42.0
check3
85.5
check3
66.0
check3
22.0
check3
180.0
check3
81.0
check3
73.5
check3
38.5
check3
585.0
check3
14.0
check3
26.0
check3
56.5
check3
22.0
check3
134.5
check3
14.0
check3
29.0
check3
46.5
check3
24.0
check3
14.0
check3
196.0
check3
20.0
check3
71.5
check3
14.0
check3
14.0
check3
55.0
check3
502.0
check3
14.0
check3
23.0
check3
20.0
check3
18.0
check3
14.0
check3
352.5
check3
39.0
check3
324.0
check3
14.0
check3
66.0
check3
43.0
check3
589.0
check3
136.0
check3
144.0
check3
39.5
check3
55.0
check3
20.0
check3
92.0
check3


check3
18.0
check3
58.5
check3
24.0
check3
34.5
check3
38.5
check3
363.5
check3
114.0
check3
48.0
check3
75.0
check3
47.0
check3
22.0
check3
128.0
check3
31.5
check3
26.5
check3
28.0
check3
28.0
check3
28.0
check3
21.5
check3
36.5
check3
43.0
check3
134.0
check3
83.0
check3
167.0
check3
176.5
check3
122.5
check3
364.5
check3
36.0
check3
89.0
check3
88.5
check3
20.5
check3
14.0
check3
196.0
check3
14.0
check3
14.0
check3
18.0
check3
78.0
check3
218.0
check3
78.0
check3
119.5
check3
94.5
check3
116.5
check3
190.5
check3
14.0
check3
132.0
check3
60.0
check3
152.0
check3
14.0
check3
28.0
check3
14.0
check3
441.0
check3
18.5
check3
14.0
check3
130.5
check3
148.0
check3
274.5
check3
42.5
check3
329.5
check3
55.0
check3
256.0
check3
412.5
check3
14.0
s2t7.jpg
s2
[[[1219 1398]]

 [[1217 1400]]

 [[1221 1400]]]
check2
check3
8.0
check3
8.0
check3
13.0
check3
27.0
check3
12.0
check3
12.0
check3
13.0
check3
136.0
check3
112.0
check3
70.0
check3
56.0
check3
32.0
check3
32.0
check3
29.0
check3
57.5

[[[1219 1398]]

 [[1217 1400]]

 [[1221 1400]]]
check2
check3
107.5
check3
120.0
check3
137.5
check3
14.0
check3
61.0
check3
23.0
check3
30.0
check3
124.0
check3
14.0
check3
42.0
check3
37.0
check3
14.0
check3
18.0
check3
193.5
check3
14.0
check3
368.0
check3
3035.0
check3
30.0
check3
218.5
check3
45.5
check3
47.0
check3
22.0
check3
2487.0
check3
417.5
check3
318.0
check3
399.5
check3
45.0
check3
87.0
check3
14.0
check3
63.5
check3
78.5
check3
14.0
check3
37.0
check3
14.0
check3
41.5
check3
14.0
check3
31.0
check3
8.0
check3
518.0
check3
14.0
check3
49.0
check3
107.0
check3
29.5
check3
18.0
check3
40.0
check3
14.0
check3
22.0
check3
154.5
check3
26.5
check3
30.0
check3
56.0
check3
75.5
check3
14.0
check3
391.5
check3
14.0
check3
375.5
check3
38.5
check3
14.0
check3
18.0
check3
18.0
check3
218.5
check3
202.0
check3
91.5
check3
128.5
check3
27.5
check3
14.0
check3
16.0
check3
25.0
check3
27.5
check3
49.5
check3
16.0
check3
246.5
check3
8.0
check3
14.0
check3
14.0
check3
93.5
check3
14.0


check3
63.0
check3
14.0
check3
167.5
check3
22.0
check3
252.5
check3
38.0
check3
18.0
check3
6040.5
check3
45.0
check3
18.0
check3
60.0
check3
52.5
check3
1986.0
check3
22.0
check3
122.0
check3
502.5
check3
58.0
check3
30.0
check3
113.0
check3
997.5
check3
1157.0
check3
337.0
check3
53.5
check3
121.0
check3
83.5
check3
40.0
check3
72.0
check3
18.0
check3
59.0
check3
14.0
check3
313.0
check3
104.5
check3
30.0
check3
97.5
check3
72.5
check3
128.0
check3
56.0
check3
25.0
check3
248.0
check3
14.0
check3
14.0
check3
260.0
check3
18.0
check3
14.0
check3
14.0
check3
973.0
check3
14.0
check3
22.0
check3
24.0
check3
14.0
check3
18.0
check3
16.0
check3
89.0
check3
41.5
check3
23.0
check3
28.5
check3
537.0
check3
14.0
check3
288.0
check3
75.5
check3
14.0
check3
623.0
check3
610.5
check3
72.5
check3
14.0
check3
88.0
check3
21.5
check3
996.0
check3
26.0
check3
14.0
check3
79.5
check3
75.0
check3
61.5
check3
41.5
check3
362.0
check3
44.5
check3
22.0
check3
18.0
check3
18.0
check3
16.0
check3
14.0
ch

check3
358.5
check3
100.5
check3
14.0
check3
86.0
check3
33.0
check3
14.0
check3
95.0
check3
28.0
check3
299.5
check3
14.0
check3
100.0
check3
88.5
check3
33.0
check3
125.0
check3
46.0
check3
106.0
check3
26.0
check3
14.0
check3
29.0
check3
14.0
check3
14.0
check3
31.0
check3
83.5
check3
47.0
check3
274.0
check3
89.0
check3
150.0
check3
58.0
check3
23.0
check3
64.0
check3
44.5
check3
287.0
check3
59.0
check3
129.0
check3
292.0
check3
31.5
check3
996.0
check3
67.0
check3
41.5
check3
14.0
check3
303.5
check3
57.5
check3
14.0
check3
122.0
check3
87.5
check3
61.5
check3
42.5
check3
23.0
check3
22.0
check3
30.0
check3
28.0
check3
18.0
check3
208.0
check3
32.0
check3
24.0
check3
3696.5
check3
25.0
check3
22.0
check3
149.5
check3
39.0
check3
40.0
check3
44.0
check3
772.5
check3
69.5
check3
22.0
check3
207.0
check3
64.0
check3
114.5
check3
168.0
check3
276.5
check3
29.5
check3
91.0
check3
64.0
check3
163.0
check3
30.0
check3
16.0
check3
64.0
check3
53.0
check3
34.0
check3
72.0
check3
109.0
che

[[[1219 1398]]

 [[1217 1400]]

 [[1221 1400]]]
check2
check3
104.0
check3
38.5
check3
13.0
check3
25.0
check3
132.0
check3
55.0
check3
134.0
check3
52.0
check3
209.0
check3
28.0
check3
60.0
check3
111.5
check3
80.0
check3
91.0
check3
57.0
check3
145.5
check3
45.5
check3
191.0
check3
162.0
check3
132.0
check3
126.5
check3
96.0
check3
29.0
check3
98.0
check3
169.5
check3
315.5
check3
54.5
check3
14.0
check3
244.5
check3
20.0
check3
410.5
check3
39.0
check3
88.5
check3
64.0
check3
122.0
check3
14.0
check3
85.5
check3
73.0
check3
48.0
check3
57.5
check3
29.5
check3
148.0
check3
109.0
check3
18.0
check3
92.0
check3
7069.5
check3
30.5
check3
89.5
check3
20.0
check3
114.0
check3
57.0
check3
30.5
check3
116.0
check3
276.0
check3
80.5
check3
143.0
check3
225.0
check3
149.5
check3
76.0
check3
18.0
check3
81.5
check3
942.5
check3
121.5
check3
46.5
check3
291.0
check3
249.0
check3
20.0
check3
454.0
check3
14.0
check3
14.0
check3
438.0
check3
190.5
check3
107.5
check3
211.5
check3
505.0
check3
314

[[[1219 1398]]

 [[1217 1400]]

 [[1221 1400]]]
check2
check3
11.0
check3
11.0
check3
20.5
check3
28.5
check3
19.0
check3
156.5
check3
50.0
check3
14.0
check3
25.0
check3
25.0
check3
14.0
check3
394.5
check3
31.5
check3
18.0
check3
20.0
check3
29.0
check3
14.0
check3
14.0
check3
68.0
check3
14.0
check3
14.0
check3
21.5
check3
26.0
check3
14.0
check3
57.5
check3
82.0
check3
34.5
check3
64.0
check3
14.0
check3
170.0
check3
14.0
check3
14.0
check3
63.0
check3
26.0
check3
23.0
check3
25.5
check3
22.0
check3
14.0
check3
18.0
check3
14.0
check3
14.0
check3
14.0
check3
14.0
check3
107.5
check3
307.5
check3
23.0
check3
298.0
check3
689.0
check3
574.0
check3
338.0
check3
20.0
check3
196.0
check3
165.0
check3
25.0
check3
94.5
check3
28.0
check3
26.0
check3
18.0
check3
16.0
check3
3284.0
check3
207.0
check3
177.5
check3
46.0
check3
161.0
check3
57.0
check3
32.0
check3
57.0
check3
593.5
check3
32.5
check3
75.5
check3
421.0
check3
384.0
check3
156.0
check3
730.5
check3
75.5
check3
69.0
check3
14.0


41.5
check3
22.0
check3
39.0
check3
14.0
check3
1163.5
check3
294.0
check3
385.0
check3
14.0
check3
751.0
check3
23.0
check3
54.0
check3
22.0
check3
81.5
check3
723.5
check3
256.5
check3
23.0
check3
54.0
check3
150.0
check3
290.0
check3
518.5
check3
101.5
check3
18.0
check3
589.0
check3
14.0
check3
14.0
check3
38.0
check3
710.0
check3
307.5
check3
844.5
check3
6519.5
check3
113.0
check3
26.5
check3
23.0
check3
154.0
check3
140.0
check3
166.0
check3
154.0
check3
23.0
check3
14.0
check3
225.0
check3
702.0
check3
43.0
check3
156.0
check3
32.0
check3
20.0
check3
245.5
check3
378.0
check3
14973.0
check3
2864.0
check3
194.0
check3
14.0
check3
140.5
check3
139.5
check3
139.5
check3
78488.0
check3
200.5
check3
157.0
check3
719.0
check3
2341.0
check3
14.0
check3
461.0
check3
293.5
check3
48.0
check3
2341.5
bct9.jpg
bc
[[[1219 1398]]

 [[1217 1400]]

 [[1221 1400]]]
check2
check3
127.5
check3
57.5
check3
136.5
check3
18.0
check3
16.0
check3
8.0
check3
58.0
check3
472.5
check3
9587.0
check3
14.0


check3
132.0
check3
40.5
check3
18.0
check3
248.5
check3
26.5
check3
55.0
check3
172.0
check3
57.0
check3
54.0
check3
14.0
check3
18.0
check3
18.0
check3
91.0
check3
180.0
check3
62.5
check3
130.0
check3
43.0
check3
452.5
check3
90.0
check3
23.0
check3
40.0
check3
102.0
check3
645.0
check3
30.0
check3
44.0
check3
24.0
check3
118.0
check3
429.0
check3
64.5
check3
305.5
check3
53.0
check3
173.5
check3
56.0
check3
445.5
check3
47.0
check3
120.0
check3
82.0
check3
14.0
check3
234.0
check3
21.5
check3
33.0
check3
131.0
check3
26.0
check3
50.0
check3
357.0
check3
183.5
check3
143.0
check3
139.5
check3
33.0
check3
67.0
check3
30.0
check3
22.0
check3
137.0
check3
93.0
check3
206.5
check3
33.0
check3
95.0
check3
292.5
check3
71.5
check3
132.0
check3
39.0
check3
75.0
check3
51.0
check3
185.5
check3
120.0
check3
45.5
check3
87.0
check3
28.0
check3
79.0
check3
80.5
check3
83.5
check3
28.0
check3
130.5
check3
54.0
check3
14.0
check3
131.0
check3
121.0
check3
65.0
check3
25.0
check3
267.5
check3
172

[[[1219 1398]]

 [[1217 1400]]

 [[1221 1400]]]
check2
check3
8.0
check3
14.0
check3
56.0
check3
104.0
check3
32.0
check3
17.0
check3
14.0
check3
16.0
check3
72.0
check3
40.0
check3
164.5
check3
59.5
check3
30.0
check3
36.0
check3
55.5
check3
40.0
check3
36.0
check3
131.5
check3
36.0
check3
42.0
check3
144.5
check3
42.0
check3
222.0
check3
216.0
check3
37.0
check3
94.5
check3
241.5
check3
81.5
check3
372.0
check3
18.0
check3
507.5
check3
790.0
check3
53.0
check3
39.0
check3
18.0
check3
25.0
check3
79.5
check3
42.0
check3
23.0
check3
359.5
check3
228.0
check3
1463.0
check3
156.0
check3
18.0
check3
395.5
check3
77.5
check3
166.0
check3
1950.5
check3
529.5
check3
91.5
check3
22.0
check3
249.0
check3
14.0
check3
441.0
check3
35.0
check3
490.0
check3
6224.0
check3
132.0
check3
123.0
check3
114.0
check3
32.0
check3
163.0
check3
271.0
check3
88.5
check3
133.5
check3
73.0
check3
598.5
check3
89.5
check3
61.5
check3
48.0
check3
166.5
check3
379.5
check3
1632.0
check3
249.0
check3
218.0
check3
7

check3
121.0
check3
109.0
check3
73.5
check3
22.0
check3
97.5
check3
103.5
check3
18.0
check3
20.0
check3
93.5
check3
93.5
check3
529.0
check3
533.0
check3
14.0
check3
71.5
check3
42.0
check3
33.5
check3
130.5
check3
20.0
check3
14.0
check3
139.0
check3
14.0
check3
72.0
check3
20.0
check3
54.5
check3
227.0
check3
568.5
check3
132.5
check3
21.5
check3
372.0
check3
86.0
check3
18.0
check3
14.0
check3
14.0
check3
14.0
check3
131.0
check3
20.0
check3
159.0
check3
807.5
check3
33.0
check3
332.5
check3
14.0
check3
111.0
check3
51.0
check3
14.0
check3
18.0
check3
14.0
check3
139.0
check3
144.0
check3
25.0
check3
33.0
check3
21.5
check3
356.5
check3
14.0
check3
418.5
check3
33.0
check3
809.0
check3
14.0
check3
127.0
check3
207.0
check3
25.0
check3
18.0
check3
164.0
check3
33.0
check3
14.0
check3
99.0
check3
41.0
check3
29.5
check3
130.0
check3
14.0
check3
157.0
check3
14.0
check3
240.0
check3
14.0
check3
14.0
check3
119.5
check3
20.0
check3
79.0
check3
22.0
check3
126.0
check3
104.5
check3
53.

check3
62.0
check3
21.5
check3
22.0
check3
63.0
check3
54.0
check3
93.0
check3
45.5
check3
25.5
check3
128.0
check3
166.0
check3
18.0
check3
26.0
check3
14.0
check3
1324.0
check3
9.0
check3
23.0
check3
18.0
check3
30.0
check3
1135.0
check3
349.5
check3
14.0
check3
50.0
check3
14.0
check3
55.0
check3
29.0
check3
27.0
check3
14.0
check3
93.5
check3
104.0
check3
46.0
check3
333.0
check3
18.0
check3
28.0
check3
178.5
check3
14.0
check3
14.0
check3
72.0
check3
21.5
check3
57.0
check3
20.0
check3
108.5
check3
26.0
check3
26.0
check3
43.5
check3
22.0
check3
14.0
check3
617.5
check3
85.0
check3
34.0
check3
14.0
check3
21.5
check3
45.0
check3
55.5
check3
171.0
check3
167.5
check3
34.0
check3
18.0
check3
79.5
check3
88.0
check3
29.0
check3
14.0
check3
14.0
check3
96.5
check3
41.0
check3
61.5
check3
25.5
check3
55.5
check3
29.5
check3
7.0
check3
162.0
check3
28.0
check3
271.5
check3
29.5
check3
23.0
check3
18.0
check3
29.5
check3
14.0
check3
45.0
check3
27.0
check3
22.0
check3
22.0
check3
8.0
che

check3
55.0
check3
21.5
check3
72.0
check3
182.5
check3
40.0
check3
20.0
check3
56.0
check3
14.0
check3
43.0
check3
31.5
check3
36.0
check3
39.0
check3
440.0
check3
1159.5
check3
18.0
check3
193.0
check3
73.0
check3
29.5
check3
18.0
check3
54.5
check3
25.5
check3
46.0
check3
34.5
check3
102.0
check3
46.0
check3
20.0
check3
54.0
check3
14.0
check3
34.0
check3
30.0
check3
20.0
check3
41.0
check3
88.5
check3
206.0
check3
14.0
check3
84.0
check3
146.5
check3
14.0
check3
18.0
check3
261.0
check3
14.0
check3
34.5
check3
25.0
check3
14.0
check3
669.5
check3
101.5
check3
32.0
check3
93.0
check3
114.0
check3
188.5
check3
14.0
check3
67.5
check3
104.0
check3
26.0
check3
34.0
check3
323.0
check3
18.0
check3
114.5
check3
24.0
check3
14.0
check3
637.0
check3
1494.5
check3
18.0
check3
18.0
check3
14.0
check3
549.5
check3
25.0
check3
14.0
check3
99.5
check3
472.5
check3
37.5
check3
186.5
check3
87.0
check3
230.5
check3
26.0
check3
786.5
check3
14.0
check3
23.0
check3
107.5
check3
14.0
check3
18.0
che

44.5
check3
52.0
check3
21.5
check3
38.0
check3
35.0
check3
14.0
check3
40.0
check3
54.0
check3
71.0
check3
14.0
check3
14.0
check3
34.5
check3
56.0
check3
18.0
check3
14.0
check3
14.0
check3
18.0
check3
32.5
check3
51.0
check3
101.0
check3
45.0
check3
21.5
check3
14.0
check3
30.0
check3
30.0
check3
14.0
check3
14.0
check3
51.0
check3
18.0
check3
18.0
check3
149.5
check3
18.0
check3
25.0
check3
30.0
check3
26.0
check3
54.0
check3
23.0
check3
14.0
check3
326.0
check3
14.0
check3
801.5
check3
21.5
check3
18.0
check3
21.5
check3
18.0
check3
26.5
check3
214.0
check3
490.0
check3
64.5
check3
25.0
check3
18.0
check3
14.0
check3
14.0
check3
14.0
check3
14.0
check3
22.0
check3
24.0
check3
367.5
check3
14.0
check3
26.5
check3
14.0
check3
37.0
check3
60.5
check3
14.0
check3
34.0
check3
14.0
check3
14.0
check3
110.0
check3
18.0
check3
29.0
check3
41.5
check3
18.0
check3
14.0
check3
2041.0
check3
822.5
check3
14.0
check3
21.5
check3
18.0
check3
14.0
check3
22.0
check3
14.0
check3
21.5
check3
76.0


[[[1219 1398]]

 [[1217 1400]]

 [[1221 1400]]]
check2
check3
56.0
check3
65.0
check3
52.0
check3
113.0
check3
30.5
check3
115.5
check3
248.0
check3
39.5
check3
796.5
check3
46.5
check3
111.5
check3
16.0
check3
109.0
check3
77.0
check3
105.5
check3
44.0
check3
144.0
check3
78.5
check3
53.0
check3
1493.0
check3
63.0
check3
20.0
check3
561.0
check3
14.0
check3
110.5
check3
24.0
check3
1801.0
check3
310.5
check3
56.5
check3
227.0
check3
37.0
check3
29.5
check3
511.0
check3
205.0
check3
529.0
check3
646.5
check3
26.5
check3
112.0
check3
61.0
check3
71.5
check3
51.5
check3
61.5
check3
111.0
check3
270.0
check3
28.0
check3
14968.0
check3
40.0
check3
79.5
check3
127.5
check3
64.0
check3
44.5
check3
97.0
check3
88.0
check3
806.0
check3
81.0
check3
499.5
check3
196.0
check3
101.5
check3
47.0
check3
24.0
check3
47.0
check3
93.0
check3
594.0
check3
88.5
check3
387.5
check3
20.0
check3
123.0
check3
16.0
check3
166.5
check3
126.5
check3
14.0
check3
1279.5
check3
140.0
check3
54.0
check3
633.5
check

check3
29938.0
check3
189.0
check3
132980.0
check3
279.0
check3
14.0
check3
355.5
check3
128.0
check3
6011.0
s4t10.jpg
s4
[[[1219 1398]]

 [[1217 1400]]

 [[1221 1400]]]
check2
check3
8.0
check3
8.0
check3
14.0
check3
11.0
check3
14.0
check3
44.0
check3
12.0
check3
12.0
check3
264.0
check3
72.0
check3
200.0
check3
68.0
check3
68.0
check3
28.0
check3
24.5
check3
22.0
check3
20.0
check3
23.0
check3
68.0
check3
42.0
check3
182.5
check3
284.5
check3
24.5
check3
352.0
check3
102.0
check3
114.5
check3
102.0
check3
56.0
check3
44.0
check3
36.0
check3
36.0
check3
311.5
check3
746.5
check3
123.0
check3
60.0
check3
324.5
check3
24.5
check3
26.0
check3
14.0
check3
66.0
check3
20.0
check3
179.5
check3
25.0
check3
796.0
check3
140.0
check3
108.5
check3
419.0
check3
11.0
check3
463.0
check3
1415.5
check3
23.0
check3
233.0
check3
352.0
check3
229.0
check3
25.0
check3
3866.0
check3
427.0
check3
38.5
check3
101.5
check3
3389.5
check3
49.5
check3
86.0
check3
271.0
check3
1178.5
check3
16.0
check3
20.0
c

check3
27.0
check3
167.5
check3
14.0
check3
90.5
check3
33.0
check3
175.0
check3
31.5
check3
58.0
check3
38.0
check3
14.0
check3
61.0
check3
47.0
check3
30.0
check3
23.0
check3
84.0
check3
126.5
check3
723.0
check3
86.5
check3
26.5
check3
18.0
check3
23.0
check3
14.0
check3
153.5
check3
81.0
check3
47.0
check3
21.5
check3
113.0
check3
88.0
check3
172.5
check3
167.5
check3
146.5
check3
14.0
check3
87.5
check3
245.0
check3
34.5
check3
18.0
check3
248.5
check3
34.5
check3
37.0
check3
14.0
check3
92.5
check3
18.0
check3
41.5
check3
14.0
check3
23.0
check3
57.0
check3
34.0
check3
220.5
check3
33.0
check3
28.5
check3
75.0
check3
14.0
check3
384.0
check3
25.0
check3
34.0
check3
37.5
check3
42.5
check3
141.0
check3
295.0
check3
63.5
check3
16.0
check3
20.0
check3
54.5
check3
498.5
check3
18.0
check3
33.0
check3
20.0
check3
116.0
check3
23.0
check3
306.5
check3
199.0
check3
14.0
check3
33.0
check3
79.0
check3
50.5
check3
56.5
check3
72.0
check3
26.0
check3
14.0
check3
14.0
check3
14.0
check3
41

[[[1219 1398]]

 [[1217 1400]]

 [[1221 1400]]]
check2
check3
7.0
check3
7.0
check3
7.0
check3
5.5
check3
16.0
check3
31.0
check3
13.0
check3
116.5
check3
22.0
check3
31.5
check3
379.0
check3
20.0
check3
23.0
check3
59.5
check3
32.5
check3
34.5
check3
97.5
check3
32.5
check3
279.0
check3
110.0
check3
103.0
check3
105.5
check3
98.5
check3
459.0
check3
111.5
check3
46.0
check3
170.0
check3
387.5
check3
790.5
check3
20.0
check3
23.0
check3
18.5
check3
562.0
check3
49.5
check3
20.0
check3
41.5
check3
20.0
check3
478.5
check3
249.0
check3
132.0
check3
20.0
check3
41.5
check3
37.5
check3
424.5
check3
217.5
check3
445.5
check3
5740.0
check3
69.0
check3
24.5
check3
2571.0
check3
234.5
check3
81.5
check3
14.0
check3
120.0
check3
18.0
check3
25.0
check3
203.0
check3
116.5
check3
14.0
check3
14.0
check3
162.5
check3
16.0
check3
480.5
check3
22.0
check3
44.0
check3
254.5
check3
49.0
check3
169.5
check3
176.0
check3
714.5
check3
50.5
check3
256.5
check3
40.5
check3
14.0
check3
245.0
check3
20.0
che

check3
18.0
check3
28.5
check3
43.5
check3
356.5
check3
33.0
check3
357.0
check3
14.0
check3
24.0
check3
205.0
check3
165.0
check3
479.0
check3
40.0
check3
3279.0
check3
70.0
check3
646.0
check3
16.0
check3
35.0
check3
42.0
check3
14.0
check3
74.0
check3
24.5
check3
97.0
check3
810.0
check3
39.0
check3
25.0
check3
105.5
check3
25.0
check3
35.0
check3
32.0
check3
7110.5
check3
235.0
check3
47.0
check3
500.0
check3
1238.0
check3
24.0
check3
68.5
check3
414.0
check3
20.0
check3
196.5
check3
6706.0
check3
67.0
check3
43.0
check3
593.5
check3
57.0
check3
60.0
check3
60.5
check3
43.0
check3
106.5
check3
95.0
check3
257.0
check3
14.0
check3
25.0
check3
128.0
check3
548.0
check3
127.0
check3
239.0
check3
62.5
check3
64.5
check3
65.0
check3
127.0
check3
43.0
check3
611.0
check3
58.5
check3
16.0
check3
30.0
check3
76.0
check3
26.0
check3
14.0
check3
14.0
check3
189.0
check3
29.0
check3
448.0
check3
55.5
check3
140.5
check3
29.0
check3
279.0
check3
169.0
check3
8.0
check3
69.0
check3
948.0
check3

### Bill's photos in the control group

In [ ]:
import os
import cv2
import numpy as np

folder = 'data/B/experiment2/'

for i in range(1, 2, 1):
    day = 't'+ str(i)
    path = folder + day 
    idx = 0
    for filename in os.listdir(path):
        if filename.startswith('bc') and filename.endswith('.jpg'):
            num = ''
            j = 0
            while True:
                if filename[j] == 't':
                    break
                else:
                    num = num + filename[j]
                    j += 1
            print(filename)
            print(num)
            #############################################
            # After selecting the correct HSV
            #############################################
            img = cv2.imread(path + '/' + filename)
            #print(img)
            #convert to HSA
            imgHSV = cv2.cv2.cvtColor(img, cv2.COLOR_BGR2HSV)
            #select the filtered image
            lower = np.array([21,36,44])
            upper = np.array([55,255,255])
            #filtered image
            mask = cv2.inRange(imgHSV, lower, upper)
            #using filtered images to create new image 
            #this is adding two images together 
            imgResult = cv2.bitwise_and(img,img, mask = mask)
 
            # =============================================================================
            # img = imgResult.copy() 
            # imgContour = imgResult.copy()
            # =============================================================================

            imgGray = cv2.cvtColor(imgResult, cv2.COLOR_BGR2GRAY)
            #sigma, the higher the value, the more blur you get
            imgBlur = cv2.GaussianBlur(imgGray,(7,7),1)
            
            #cv2.imwrite('banana_images/B/' +day + '/'+ num + '.png', new_img) 
            (cnts, _) = cv2.findContours(imgBlur, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE) 
            #contours = sorted(cnts, key=cv2.contourArea, reverse=False)
        #    idx = 0 

            for c in cnts: 

                area = cv2.contourArea(c)
                if area > 1000:
                    x,y,w,h = cv2.boundingRect(c) 
                    if w>400 and h>400:
                        idx+=1 
                        new_img=imgResult[y:y+h,x:x+w] 
                        #print('banana_images/N/' +day + '/'+ num + '.png')
                        cv2.imwrite('banana_images/B/' +day + '/'+ num + '.png', new_img) 

bct1.jpg
bc


### For Justin's photos

In [ ]:
import os
import cv2
import numpy as np

folder = 'data/J/'

for i in range(1, 11, 1):
    day = 't'+ str(i)
    path = folder + 'experiment3/' + day + '/banana'
    idx = 0
    for filename in os.listdir(path):
        if filename.endswith('.jpg'):
            num = ''
            j = 0
            while True:
                if filename[j] == 't':
                    break
                else:
                    num = num + filename[j]
                    j += 1
            print(filename)
            print(num)
            #############################################
            # After selecting the correct HSV
            #############################################
            img = cv2.imread(path + '/' + filename)
            #print(img)
            #convert to HSA
            imgHSV = cv2.cv2.cvtColor(img, cv2.COLOR_BGR2HSV)
            #select the filtered image
            lower = np.array([21,36,44])
            upper = np.array([55,255,255])
            #filtered image
            mask = cv2.inRange(imgHSV, lower, upper)
            #using filtered images to create new image 
            #this is adding two images together 
            imgResult = cv2.bitwise_and(img,img, mask = mask)
 
            # =============================================================================
            # img = imgResult.copy() 
            # imgContour = imgResult.copy()
            # =============================================================================

            imgGray = cv2.cvtColor(imgResult, cv2.COLOR_BGR2GRAY)
            #sigma, the higher the value, the more blur you get
            imgBlur = cv2.GaussianBlur(imgGray,(7,7),1)

            (cnts, _) = cv2.findContours(imgBlur, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE) 
        #    idx = 0 
            for c in cnts: 
                area = cv2.contourArea(c)
                if area > 1000:
                    x,y,w,h = cv2.boundingRect(c) 
                    if w>400 and h>400:
                        print('check4')
                        idx+=1 
                        new_img=imgResult[y:y+h,x:x+w] 
                        print('banana_images/N/' +day + '/'+ num + '.png')
                        cv2.imwrite('banana_images/N/' +day + '/'+ num + '.png', new_img) 

In [ ]:
import cv2
import numpy as np
#read the image


path = 'nobu1.jpg'
#############################################
# After selecting the correct HSV
#############################################
img = cv2.imread(path)
#img = cv2.resize(img,(300,400))

#convert to HSA
imgHSV = cv2.cv2.cvtColor(img, cv2.COLOR_BGR2HSV)
#select the filtered image
lower = np.array([21,36,44])
upper = np.array([55,255,255])

#filtered image
mask = cv2.inRange(imgHSV, lower, upper)

#using filtered images to create new image 
#this is adding two images together 
imgResult = cv2.bitwise_and(img,img, mask = mask)

# =============================================================================
# img = imgResult.copy() 
# imgContour = imgResult.copy()
# =============================================================================

imgGray = cv2.cvtColor(imgResult, cv2.COLOR_BGR2GRAY)
#sigma, the higher the value, the more blur you get
imgBlur = cv2.GaussianBlur(imgGray,(7,7),1)

(cnts, _) = cv2.findContours(imgBlur, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE) 
idx = 0 
for c in cnts: 
    area = cv2.contourArea(c)
    if area > 1000:
        x,y,w,h = cv2.boundingRect(c) 
        if w>100 and h>100: 
            idx+=1 
            new_img=imgResult[y:y+h,x:x+w] 
            cv2.imwrite('banana_images/N/day1/' + str(idx) + '.png', new_img) 